package Vistas;

public class MenuFojador extends javax.swing.JFrame {

    public MenuFojador() {
        initComponents();
        pnlCrearFoja.setVisible(false);
        pnlCargarFoja.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCargarFoja = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlCrearFoja = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblObras = new javax.swing.JTable();
        barraMenu = new javax.swing.JMenuBar();
        menuSesion = new javax.swing.JMenu();
        itemCerrarSesion = new javax.swing.JMenuItem();
        menuFojas = new javax.swing.JMenu();
        itemCrearFoja = new javax.swing.JMenuItem();
        itemCargarFoja = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú de Fojador");

        jLabel1.setText("panel cargar foja");

        javax.swing.GroupLayout pnlCargarFojaLayout = new javax.swing.GroupLayout(pnlCargarFoja);
        pnlCargarFoja.setLayout(pnlCargarFojaLayout);
        pnlCargarFojaLayout.setHorizontalGroup(
            pnlCargarFojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(pnlCargarFojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCargarFojaLayout.createSequentialGroup()
                    .addGap(258, 258, 258)
                    .addComponent(jLabel1)
                    .addContainerGap(258, Short.MAX_VALUE)))
        );
        pnlCargarFojaLayout.setVerticalGroup(
            pnlCargarFojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
            .addGroup(pnlCargarFojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCargarFojaLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(jLabel1)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );

        tblObras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre", "Localidad", "Empresa", "Fecha de inicio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblObras.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblObras);
        if (tblObras.getColumnModel().getColumnCount() > 0) {
            tblObras.getColumnModel().getColumn(0).setResizable(false);
            tblObras.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblObras.getColumnModel().getColumn(1).setResizable(false);
            tblObras.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblObras.getColumnModel().getColumn(2).setResizable(false);
            tblObras.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblObras.getColumnModel().getColumn(3).setResizable(false);
            tblObras.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblObras.getColumnModel().getColumn(4).setResizable(false);
            tblObras.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        javax.swing.GroupLayout pnlCrearFojaLayout = new javax.swing.GroupLayout(pnlCrearFoja);
        pnlCrearFoja.setLayout(pnlCrearFojaLayout);
        pnlCrearFojaLayout.setHorizontalGroup(
            pnlCrearFojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearFojaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCrearFojaLayout.setVerticalGroup(
            pnlCrearFojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearFojaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuSesion.setText("Sesión");

        itemCerrarSesion.setText("Cerrar sesión");
        menuSesion.add(itemCerrarSesion);

        barraMenu.add(menuSesion);

        menuFojas.setText("Fojas");

        itemCrearFoja.setText("Crear foja");
        itemCrearFoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearFojaActionPerformed(evt);
            }
        });
        menuFojas.add(itemCrearFoja);

        itemCargarFoja.setText("Cargar foja");
        itemCargarFoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCargarFojaActionPerformed(evt);
            }
        });
        menuFojas.add(itemCargarFoja);

        barraMenu.add(menuFojas);

        menuConsultas.setText("Consultas");
        barraMenu.add(menuConsultas);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCrearFoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCargarFoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCrearFoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCargarFoja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCrearFojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearFojaActionPerformed
        pnlCargarFoja.setVisible(false);
        pnlCrearFoja.setVisible(true);
    }//GEN-LAST:event_itemCrearFojaActionPerformed

    private void itemCargarFojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCargarFojaActionPerformed
        pnlCrearFoja.setVisible(false);
        pnlCargarFoja.setVisible(true);
    }//GEN-LAST:event_itemCargarFojaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemCargarFoja;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JMenuItem itemCrearFoja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuFojas;
    private javax.swing.JMenu menuSesion;
    private javax.swing.JPanel pnlCargarFoja;
    private javax.swing.JPanel pnlCrearFoja;
    private javax.swing.JTable tblObras;
    // End of variables declaration//GEN-END:variables
}
