/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
/**
 *
 * @author Garma
 */
public class MenuCertificador extends javax.swing.JFrame {
    
    private ListSelectionModel tblListFojasModel;
     private ListSelectionModel tblListCertificadosModel;
    private Connection con;
    private Statement sqlStmn;
    private String certiSeleccionado;
    private CallableStatement callSqlStmn;
    private ResultSet fojasCertificables;
    private ResultSet certificadosAbiertos;
    private List<String> numObras = new ArrayList();
    private String queryFojasCertificables = "SELECT f.idfoja, o.nomobra, o.numobra FROM sol.FOJA f \n" +
                                            "INNER JOIN sol.OBRA o ON o.idobra = f.idobra\n" +
                                            "WHERE sol.fun_estacertificada(f.idfoja)=0";
    private String queryCertificadosAbiertos = "SELECT o.numobra, o.nomobra, cp.nrocertificado FROM sol.Obra o\n" +
                                                "INNER JOIN sol.certipago cp on cp.idobra = o.idobra\n" +
                                                "INNER JOIN sol.certiobra co on co.nrocertificado = cp.nrocertificado AND co.idobra = o.idobra\n" +
                                                "WHERE sol.fun_estacertificada(co.idfoja)=1";
   
    
    
    
    public MenuCertificador(Connection con, Statement sqlStmn) {
        this.con = con;
        this.sqlStmn = sqlStmn;
        initComponents();
        pnlCrearCertificados.setVisible(false);
        pnlCerrarCertificado.setVisible(false);
        tblListFojasModel = tblFojas.getSelectionModel();  
        tblListCertificadosModel = tblCertificados.getSelectionModel();         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCrearCertificados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFojas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCrearCertificados = new javax.swing.JButton();
        pnlCerrarCertificado = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCertificados = new javax.swing.JTable();
        btnCerrarCertificado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSesion = new javax.swing.JMenu();
        itemCerrarSesion = new javax.swing.JMenuItem();
        menuCertificados = new javax.swing.JMenu();
        itemCrearCertificados = new javax.swing.JMenuItem();
        itemCerrarCertificados = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblFojas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Foja", "Obra", "Nro Obra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFojas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFojasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFojas);
        if (tblFojas.getColumnModel().getColumnCount() > 0) {
            tblFojas.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblFojas.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        jLabel1.setText("Lista de fojas certificables");

        btnCrearCertificados.setText("Crear certificado");
        btnCrearCertificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCertificadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCrearCertificadosLayout = new javax.swing.GroupLayout(pnlCrearCertificados);
        pnlCrearCertificados.setLayout(pnlCrearCertificadosLayout);
        pnlCrearCertificadosLayout.setHorizontalGroup(
            pnlCrearCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearCertificadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCrearCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addGroup(pnlCrearCertificadosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearCertificados, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlCrearCertificadosLayout.setVerticalGroup(
            pnlCrearCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCrearCertificadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCrearCertificadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCrearCertificados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblCertificados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro Obra", "Obra", "Certificado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCertificados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCertificadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCertificados);
        if (tblCertificados.getColumnModel().getColumnCount() > 0) {
            tblCertificados.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblCertificados.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblCertificados.getColumnModel().getColumn(2).setPreferredWidth(15);
        }

        btnCerrarCertificado.setText("Cerrar Certificado");
        btnCerrarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCertificadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Certificados pendientes de cerrar");

        javax.swing.GroupLayout pnlCerrarCertificadoLayout = new javax.swing.GroupLayout(pnlCerrarCertificado);
        pnlCerrarCertificado.setLayout(pnlCerrarCertificadoLayout);
        pnlCerrarCertificadoLayout.setHorizontalGroup(
            pnlCerrarCertificadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCerrarCertificadoLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pnlCerrarCertificadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlCerrarCertificadoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        pnlCerrarCertificadoLayout.setVerticalGroup(
            pnlCerrarCertificadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCerrarCertificadoLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(pnlCerrarCertificadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarCertificado)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        menuSesion.setText("Sesión");

        itemCerrarSesion.setText("Cerrar Sesión");
        menuSesion.add(itemCerrarSesion);

        jMenuBar1.add(menuSesion);

        menuCertificados.setText("Certificados");

        itemCrearCertificados.setText("Crear certificados");
        itemCrearCertificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearCertificadosActionPerformed(evt);
            }
        });
        menuCertificados.add(itemCrearCertificados);

        itemCerrarCertificados.setText("Cerrar certificados");
        itemCerrarCertificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarCertificadosActionPerformed(evt);
            }
        });
        menuCertificados.add(itemCerrarCertificados);

        jMenuBar1.add(menuCertificados);

        menuConsultas.setText("Consultas");
        jMenuBar1.add(menuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCrearCertificados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCerrarCertificado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCrearCertificados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCerrarCertificado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCrearCertificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearCertificadosActionPerformed
        pnlCrearCertificados.setVisible(true);
        pnlCerrarCertificado.setVisible(false);
        try{
            cargarTablaFojas();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemCrearCertificadosActionPerformed

    private void cargarTablaFojas() throws SQLException{
        this.fojasCertificables = this.getFojasCertificables();
        DefaultTableModel tblFojasModel = (DefaultTableModel) tblFojas.getModel();
        tblFojasModel.setRowCount(0);
        while(fojasCertificables.next())
        {
            String idFoja = String.valueOf(fojasCertificables.getInt(1));
            String nomObra = fojasCertificables.getString(2);
            String numObra = fojasCertificables.getString(3);
            String[] tblData = {idFoja, nomObra, numObra};
            tblFojasModel.addRow(tblData);
        }
        deselectTblFojas();
    }
    
     private void cargarTablaCertificados() throws SQLException{
        
         
        this.certificadosAbiertos = this.getCertificadosAbiertos();
        DefaultTableModel tblCertificadosModel = (DefaultTableModel) tblCertificados.getModel();
        tblCertificadosModel.setRowCount(0);
        while(certificadosAbiertos.next())
        {
            String numObra = String.valueOf(certificadosAbiertos.getInt(1));
            String nomObra = certificadosAbiertos.getString(2);
            String nroCerti = String.valueOf(certificadosAbiertos.getInt(3));
            String[] tblData = {numObra, nomObra, nroCerti};
            tblCertificadosModel.addRow(tblData);
        }
        deselectTblCertificados();
    }
     
    private void deselectTblCertificados(){
        this.tblCertificados.clearSelection();
        this.btnCerrarCertificado.setEnabled(false);
    }
    
    private void deselectTblFojas(){
        this.tblFojas.clearSelection();
        this.btnCrearCertificados.setEnabled(false);
    }
    
    private ResultSet getFojasCertificables(){
        ResultSet fojasCertificables = null;
        try{
            fojasCertificables = sqlStmn.executeQuery(queryFojasCertificables);
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return fojasCertificables;
    }
    
    private ResultSet getCertificadosAbiertos(){
        ResultSet certificadosAbiertos = null;
        try{
            certificadosAbiertos = sqlStmn.executeQuery(queryCertificadosAbiertos);
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return certificadosAbiertos;
    }
   
    private void itemCerrarCertificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarCertificadosActionPerformed
        pnlCrearCertificados.setVisible(false);
        pnlCerrarCertificado.setVisible(true);
        try{
            cargarTablaCertificados();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemCerrarCertificadosActionPerformed

    private void btnCrearCertificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCertificadosActionPerformed
        try{
            callSqlStmn = con.prepareCall("{CALL sol.PRC_CREARCERTIFICADOS(?, ?)}");
            callSqlStmn.registerOutParameter(2, Types.INTEGER);
            for(String numObra: numObras){
                callSqlStmn.setInt(1, Integer.valueOf(numObra));
                callSqlStmn.execute();
                
            }
            cargarTablaFojas();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearCertificadosActionPerformed

    private void tblFojasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFojasMouseClicked
        if(this.tblListFojasModel.getSelectedItemsCount() > 0){
            btnCrearCertificados.setEnabled(true);
            this.btnCrearCertificados.setEnabled(true);
            this.numObras.clear();
            int[] index = tblFojas.getSelectedRows();
            for(int i = 0; i < tblFojas.getSelectedRowCount(); i++){
                String numObra = String.valueOf(tblFojas.getValueAt(index[i],2));
                if(!this.numObras.contains(numObra))
                {
                    this.numObras.add(numObra);
                }
            }
        }
    }//GEN-LAST:event_tblFojasMouseClicked

    private void btnCerrarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCertificadoActionPerformed
        try{
            callSqlStmn = con.prepareCall("{CALL sol.PRC_CERRARCERT(?, ?)}");
            callSqlStmn.registerOutParameter(2, Types.INTEGER);
            callSqlStmn.setInt(1, Integer.valueOf(certiSeleccionado));
            callSqlStmn.execute();
            cargarTablaCertificados();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCerrarCertificadoActionPerformed

    private void tblCertificadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCertificadosMouseClicked
        if(this.tblListCertificadosModel.getSelectedItemsCount() == 1) {
            btnCerrarCertificado.setEnabled(true);
            certiSeleccionado = String.valueOf(tblCertificados.getValueAt(tblCertificados.getSelectedRow(), 0));
            System.out.println(certiSeleccionado);
        } else {
            btnCerrarCertificado.setEnabled(false);
        }
    }//GEN-LAST:event_tblCertificadosMouseClicked

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarCertificado;
    private javax.swing.JButton btnCrearCertificados;
    private javax.swing.JMenuItem itemCerrarCertificados;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JMenuItem itemCrearCertificados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuCertificados;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuSesion;
    private javax.swing.JPanel pnlCerrarCertificado;
    private javax.swing.JPanel pnlCrearCertificados;
    private javax.swing.JTable tblCertificados;
    private javax.swing.JTable tblFojas;
    // End of variables declaration//GEN-END:variables

    
}
