prompt Importing table ITEM...
set feedback off
set define off
insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 10096, 2, 'SIST. ABASTECIMIENTO AGUA POTABLE', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 10096, 2, 'CONEXION DOMICI. AGUA DE RED', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 10096, 2, 'SIST. DESAGUES PLUVIALES', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 10096, 2, 'OBRAS COMPLEMENTARIAS', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 10096, 2, 'PERFORACION', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (6, 10096, 2, 'TANQUE ELEVADO', 6);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (7, 10096, 2, 'OBRAS DE INFRA. PRIVADA-CONEX EXISTENTE', 7);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 10098, 2, 'SIST. ABASTECIMIENTO AGUA POTABLE', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 10098, 2, 'CONEXION DOMICI. AGUA DE RED', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 10098, 2, 'SIST. DESAGUES PLUVIALES', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 10098, 2, 'OBRAS COMPLEMENTARIAS', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 10098, 2, 'PERFORACION', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (6, 10098, 2, 'TANQUE ELEVADO', 6);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (7, 10098, 2, 'OBRAS DE INFRA. PRIVADA-CONEX EXISTENTE', 7);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 10099, 2, 'SIST. ABASTECIMIENTO AGUA POTABLE', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 10099, 2, 'CONEXION DOMICI. AGUA DE RED', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 10099, 2, 'REFUGIOS', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 10099, 2, 'OBRAS COMPLEMENTARIAS', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 10099, 2, 'PERFORACION', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (6, 10099, 2, 'TANQUE ELEVADO', 6);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (7, 10099, 2, 'OBRAS DE INFRA. PRIVADA-CONEX EXISTENTE', 7);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 9990, 2, 'TRABAJOS PRELIMINARES', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 9990, 2, 'MOVIMIENTO DE SUELOS', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 9990, 2, 'RED DE AGUA POTABLE', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 9990, 2, 'CAMARAS REGULADORAS DE PRESION', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 9990, 2, 'MOVILIZACION DE OBRA', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 9994, 2, 'TRABAJOS PRELIMINARES', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 9994, 2, 'EXCAVACION Y TAPADO DE ZANJAS', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 9994, 2, 'PEOVISION DE CAÑOS DE PVC JD CLASE 10', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 9994, 2, 'COLOCACION DE CAÑERIA DE PVC C/10', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 9994, 2, 'PROVISION DE VALVULAS', 6);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (6, 9994, 2, 'ACCESORIOS ', 7);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (7, 9994, 2, 'CAMARAS PARA VALVULAS', 8);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (9, 9994, 2, 'HORMIGON', 9);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (10, 9994, 2, 'MOVILIDAD DE OBRA', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 10006, 2, 'TRABAJOS PREPARATORIOS', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 10006, 2, 'MOVIMIENTO DE SUELOS', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 10006, 2, 'ESTRUCTURA RESISETENTE', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 10006, 2, 'MAMPOSTERIA', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 10006, 2, 'AISLACIONES', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (6, 10006, 2, 'CUBIERTA DE TECHOS', 7);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (7, 10006, 2, 'REVOQUES', 6);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (8, 10006, 2, 'CIELORRASOS', 8);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (9, 10006, 2, 'CONTRAPISOS', 9);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (10, 10006, 2, 'PISOS Y ZOCALOS', 10);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (11, 10006, 2, 'REVESTIMIENTOS', 11);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (12, 10006, 2, 'CARPINTERIAS', 12);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (15, 10006, 2, 'INSTALACION DE SEGURIDAD', 17);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (16, 10006, 2, 'CRISTALES, ESPEJOS Y VIDRIOS', 15);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (17, 10006, 2, 'PINTURAS', 16);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (19, 10006, 2, 'VARIOS', 18);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (20, 10006, 2, 'INSTALACION ELECTRICA', 13);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (21, 10006, 2, 'INSTALACION SANITARIA', 14);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 10100, 2, 'REMODELACION PLAZOLETA Nº 29 ', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 10100, 2, 'REMODELACION PLAZOLETA Nº 30 - RENACER', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 10100, 2, 'REMODELACION PLAZOLETA Nº 28 - DE LAS AMERICAS', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 10100, 2, 'REMODELACION PLAZOLETA Nº 27 - NORMA D´INDIO', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 10061, 2, 'MOVIMIENTO DE SUELO', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 10061, 2, 'DEMOLICIONES', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 10061, 2, 'ESTRUCTURAS', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 10061, 2, 'REPARACION DE MAMPOSTERIA', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (6, 10061, 2, 'REVOQUES Y REVESTIMIENTOS DE FRENTE', 6);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (7, 10061, 2, 'CONTRAPISOS Y CARPETAS', 7);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (8, 10061, 2, 'PISOS', 8);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (9, 10061, 2, 'ZOCALOS', 9);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (10, 10061, 2, 'CARPINTERIA DE CHAPA', 10);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (12, 10061, 2, 'CONSTRUCCION EN SECO', 11);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (14, 10061, 2, 'PINTURAS', 12);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (15, 10061, 2, 'INSTALACION DE AIRE ACONDICIONADO', 13);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (16, 10061, 2, 'INSTALACION ELECTRICA', 14);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (23, 10061, 2, 'COLUMNAS Y PROVISION DE ENERGIA', 15);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (25, 10061, 2, 'DERECHOS', 16);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (26, 10061, 2, 'VARIOS', 17);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (27, 10061, 2, 'AMOBLAMIENTO', 18);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (30, 10061, 2, 'EQUIPAMIENTO', 19);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (31, 10061, 2, '16 CAMARAS ITAEMBÉ GUAZÚ Y 3 EN BARRIOS DE PDAS, ESTUDIOS PRELIM - INGENIERIA', 20);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (32, 10061, 2, 'CÁMARAS DOMO, CONEXIONES DE 16 CÁMARAS EN ITAEMBÉ GUAZÚ', 21);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (33, 10061, 2, 'CÁMARAS DOMOS, ENLACES, CONEXIONES DE 3 CÁMARAS EN DISTINTOS BARRIOS DE POSADAS', 22);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (34, 10061, 2, 'TABLEROS Y GABINETES EN CÁMARAS', 23);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (35, 10061, 2, 'VISUALIZACIÓN, ALMACENAMIENTO Y GESTIÓN', 24);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (36, 10061, 2, 'VISUALIZACIÓN DE DESTACAMENTOS', 25);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (37, 10061, 2, 'INSTALACIÓN E INTEGRACIÓN', 26);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (38, 10061, 2, 'MANTENIMIENTO PREVENTIVO', 27);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (40, 10061, 2, 'TRABAJOS PRELIMINARES', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (41, 10061, 2, 'FIBRA OPTICA AEREA DE MARANDU HASTA DATA CENTER DE VIDEOVIGILANCIS', 28);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 10062, 2, 'ALBINO DA ROSA NOEMI', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 10062, 2, 'ALEXANDRETE DANIELA', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 10062, 2, 'ALVES DORACILIA', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 10062, 2, 'BARBOSA DA SILVA SILVIA', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 10062, 2, 'DO SANTOS ARTURO', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (6, 10062, 2, 'ROA  MARIA', 6);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (7, 10062, 2, 'RODRIGUEZ RENE RICARDO', 7);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (8, 10062, 2, 'VIERA ANGELICA', 8);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (9, 10062, 2, 'VILLALBA  ALBERTO ANTONIO', 9);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (10, 10062, 2, 'ENGERS PAOLA NOEMI', 10);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (11, 10062, 2, 'ALVEZ MARGARITA', 11);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (12, 10062, 2, 'BURGIN MARCOS', 12);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (13, 10062, 2, 'CORREA GUILLERMO', 13);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (14, 10062, 2, 'ESCANDIEL MERCEDES', 14);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (15, 10062, 2, 'ESCHER ARTURO', 15);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (16, 10062, 2, 'FERREIRA VILMAR', 16);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (17, 10062, 2, 'FERREYRA JOSE MILTON', 17);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (18, 10062, 2, 'FREY TERESA', 18);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (19, 10062, 2, 'GOTIN DAERIO', 19);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (20, 10062, 2, 'KUMM EDUINO', 20);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (21, 10062, 2, 'OLIVERA ANTONIO', 21);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 9963, 1, 'BALKE MARLEY', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 9963, 1, 'ROLON JUAN CARLOS', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 9963, 1, 'AREA CELIA NOEMI', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 9963, 1, 'SILVA MARIO ANIBAL', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 9963, 1, 'ALVEZ SERGIO DAVID', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (6, 9963, 1, 'BREZISCKI JOSE', 6);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (7, 9963, 1, 'SANCHEZ HORACIO JUAN', 7);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (8, 9963, 1, 'ATHAIDE MARCO ANTONIO', 8);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 10042, 2, 'MOVIMIETNO DE SUELO: BIBLIOTECA ', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 10042, 2, 'ESTRUCTURA DE HºAº : BIBLIOTECA', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 10042, 2, 'ALBAÑILERIA: BIBLIOTECA', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 10042, 2, 'PISOS Y ZOCALOS BIBLIOTECA', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 10042, 2, 'CUBIERTA BIBLIOTECA', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (6, 10042, 2, 'CIELORRASO BIBLIOTECA', 6);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (7, 10042, 2, 'CARPINTERIA BIBLIOTECA', 7);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (8, 10042, 2, 'INSTALACION ELECTRICA', 8);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (9, 10042, 2, 'VIDRIOS', 9);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (10, 10042, 2, 'PINTURAS BIBLIOTECA', 10);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (11, 10042, 2, 'TRABAJOS PRELIMINARES - EDIFICIO EXIST', 11);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (12, 10042, 2, 'DEMOLICIONES- EDIFICIO EXIST', 12);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (13, 10042, 2, 'ALBAÑILERIA Y REVOQUES EDIFICIO EXIST', 13);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (14, 10042, 2, 'REVESTIMIENTOS EN EDIFICIO EXIST.', 14);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (15, 10042, 2, 'PISOS Y ZOCALOS EDIFICIO EXIST', 15);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (16, 10042, 2, 'CUBIERTA DE TECHO EDIFICIO EXIST', 16);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (17, 10042, 2, 'CIELORRASOS EDIFICIO EXIST', 17);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (18, 10042, 2, 'CARPINTERIAS EDIFICIO EXIST', 18);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (19, 10042, 2, 'PINTURA EDIFICIO EXIST.', 19);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (20, 10042, 2, 'INSTALACION ELECTRICA EDIFICIO EXIST.', 20);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (21, 10042, 2, 'INSTALACION CONTRA INCENDIO EDIFICIO EXIST', 21);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (22, 10042, 2, 'INSTALACION SANITARIA EDIFICIO EXIST', 22);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (23, 10042, 2, 'INSTALACION DE GAS', 23);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (24, 10042, 2, 'VARIOS', 24);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (10, 10048, 2, 'TRABAJOS PREPARATORIOS', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (12, 10048, 2, 'EXCAVACIONES', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (13, 10048, 2, 'PAVIMENTO PARA TRANSITO LIVIANO', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (14, 10048, 2, 'MOVILIZACION DE OBRA', 14);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (10, 10054, 2, 'TRABAJOS PREPARATORIOS', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (12, 10054, 2, 'MOVIMIENTO DE SUELOS', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (13, 10054, 2, 'PAVIMENTO TRANSITO LIVIANO', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 10084, 2, 'TRABAJOS PRELIMINARES', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 10084, 2, 'MAMPOSTERIA', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 10084, 2, 'CAPA AISLADORA', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 10084, 2, 'TECHOS', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 10084, 2, 'REVOQUES', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (6, 10084, 2, 'CIELORRASO', 6);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (7, 10084, 2, 'CONTRAPISOS', 7);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (8, 10084, 2, 'PISOS', 8);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (9, 10084, 2, 'ZOCALOS', 9);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (10, 10084, 2, 'REVESTIMIENTO', 10);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (11, 10084, 2, 'CARPINTERIA', 11);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (12, 10084, 2, 'VIDRIOS', 12);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (13, 10084, 2, 'INSTALACION ELECTRICA', 13);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (14, 10084, 2, 'INSTALACION SANITARIA', 14);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (15, 10084, 2, 'DESAGUES PLUVIALES', 15);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (16, 10084, 2, 'INSTALACION DE SEGURIDAD C/INCENDIO', 16);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (17, 10084, 2, 'INSTALACION DE GAS', 17);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (18, 10084, 2, 'PINTURA', 18);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (19, 10084, 2, 'REPAR. E INST. NUEVAS EN SUBSUELO Y SALA MAQ', 19);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (20, 10084, 2, 'VARIOS', 20);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (1, 10087, 2, 'PRELIMINARES', 1);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (2, 10087, 2, 'MOVIMIENTO DE SUELO', 2);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (3, 10087, 2, 'ESTRUCTURA DE HºAº', 3);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (4, 10087, 2, 'ALBAÑILERIA', 4);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (5, 10087, 2, 'REVESTIMIENTOS', 5);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (6, 10087, 2, 'PISOS Y ZOCALOS', 6);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (7, 10087, 2, 'MARMOLERIA', 7);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (8, 10087, 2, 'CUBIERTA DE TECHO', 8);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (9, 10087, 2, 'CIELORRASO', 9);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (10, 10087, 2, 'CARPINTERIAS', 10);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (11, 10087, 2, 'INSTALACION ELECTRICA', 11);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (12, 10087, 2, 'INSTALACION SANITARIA', 12);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (13, 10087, 2, 'INSTALACION DE GAS', 13);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (14, 10087, 2, 'INSTALACION DE SEGURIDAD', 14);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (15, 10087, 2, 'CRISTALES, ESPEJOS Y VIDRIOS', 15);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (16, 10087, 2, 'PINTURAS', 16);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (17, 10087, 2, 'SEÑALETICA', 17);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (18, 10087, 2, 'INSTALACIONES ESPECIALES', 18);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (19, 10087, 2, 'VARIOS', 19);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (20, 10087, 2, 'TANQUE DE RESERVA', 20);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (21, 10087, 2, 'CUBIERTA DE TECHO SOBRE PLAYON DEPORTIVO', 21);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (22, 10062, 2, 'OLIVERA JOSE LUIS', 22);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (23, 10062, 2, 'PEREIRA ANDRES', 23);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (24, 10062, 2, 'PEREIRA ANTUNEZ ADRIAN', 24);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (25, 10062, 2, 'PEREIRA MIGUEL ANGEL', 25);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (26, 10062, 2, 'RADKE LUIS CARLOS', 26);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (27, 10062, 2, 'RODRIGUEZ DE ALMEIDA MABEL', 27);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (28, 10062, 2, 'VACCARI JOSE', 28);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (29, 10062, 2, 'VELASO LUCIO', 29);

insert into ITEM (IDITEM, IDOBRA, IDTIPOITEM, DENITEM, ORDEN)
values (30, 10062, 2, 'WISCOW ALFREDO', 30);

prompt Done.
